# Generated by Django 4.2 on 2023-06-10 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encadreur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_inscription', models.FileField(default=None, null=True, upload_to='ficher_inscription/%Y')),
                ('validation', models.BooleanField(default=False)),
                ('annee', models.CharField(max_length=100)),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants', to='encadreur.encadreur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csd_csf', models.FileField(default=None, null=True, upload_to='ficher_soutenance/%Y')),
                ('autorisation_soutenance', models.FileField(default=None, null=True, upload_to='ficher_soutenance/%Y')),
                ('pv_soutenance', models.FileField(default=None, null=True, upload_to='ficher_soutenance/%Y')),
                ('action', models.BooleanField(default=False)),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='situation_doctorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100, null=True)),
                ('publication', models.CharField(max_length=100, null=True)),
                ('communication', models.CharField(max_length=100, null=True)),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation_doctorant', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=100, null=True)),
                ('communication', models.CharField(max_length=100, null=True)),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='reinscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscription', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('titre_sujet', models.CharField(max_length=200, null=True)),
                ('nouveau_titre_sujet', models.CharField(max_length=200, null=True)),
                ('date_premier_inscription', models.CharField(max_length=50, null=True)),
                ('nom_encadreur', models.CharField(max_length=100, null=True)),
                ('nom_co_encadreur', models.CharField(max_length=100, null=True)),
                ('nouveau_nom_encadreur', models.CharField(max_length=100, null=True)),
                ('nouveau_nom_co_encadreur', models.CharField(max_length=100, null=True)),
                ('mail_public', models.CharField(max_length=100, null=True)),
                ('mail_institutionnel', models.CharField(max_length=100, null=True)),
                ('fichier_inscription', models.FileField(default=None, null=True, upload_to='ficher_inscription/%Y')),
                ('pv_csd', models.FileField(default=None, null=True, upload_to='ficher_inscription/%Y')),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reinscription', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_annee_validation', models.BooleanField(default=False)),
                ('fichier_reinscription_passage', models.FileField(default=None, null=True, upload_to='ficher_inscription/%Y')),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscription', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('titre_sujet', models.CharField(max_length=200, null=True)),
                ('date_premier_inscription', models.CharField(max_length=50, null=True)),
                ('nom_encadreur', models.CharField(max_length=100, null=True)),
                ('nom_co_encadreur', models.CharField(max_length=100, null=True)),
                ('mail_public', models.CharField(max_length=100, null=True)),
                ('mail_institutionnel', models.CharField(max_length=100, null=True)),
                ('fichier_inscription', models.FileField(default=None, null=True, upload_to='ficher_inscription/%Y')),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscription', to='pages.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='edition_pv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_de_spécialité', models.CharField(max_length=50, null=True)),
                ('methodologie', models.CharField(max_length=50, null=True)),
                ('compétences_anglais', models.CharField(max_length=50, null=True)),
                ('communications1', models.CharField(max_length=50, null=True)),
                ('communications2', models.CharField(max_length=50, null=True)),
                ('publication1', models.CharField(max_length=50, null=True)),
                ('publication2', models.CharField(max_length=50, null=True)),
                ('publication3', models.CharField(max_length=50, null=True)),
                ('publication4', models.CharField(max_length=50, null=True)),
                ('publication5', models.CharField(max_length=50, null=True)),
                ('tic', models.CharField(max_length=50, null=True)),
                ('brevet', models.CharField(max_length=50, null=True)),
                ('total', models.CharField(max_length=50, null=True)),
                ('doctorant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edition', to='pages.doctorant')),
            ],
        ),
    ]
